# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_query_encoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='encoding',
            field=models.CharField(blank=True, default='utf-8', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='snapshot',
            field=models.BooleanField(default=True, help_text='Include in snapshot task (if enabled)'),
        ),
    ]
